# Generated by Django 4.1.2 on 2022-10-05 12:22

import django.core.validators
from django.db import migrations, models
import music_app.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), music_app.core.models.validate_chars_nums_underscore])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleTwoThreeFour',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
